src/QuestionKeyBundle/Entity/Node.php
<?php

namespace QuestionKeyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
* @ORM\Table(name="node", uniqueConstraints={@ORM\UniqueConstraint(name="public_id", columns={"tree_version_id", "public_id"})})
* @ORM\Entity(repositoryClass="QuestionKeyBundle\Entity\NodeRepository")
* @ORM\HasLifecycleCallbacks
*  @license 3-clause BSD
*  @link https://github.com/QuestionKey/QuestionKey-Core
*/
class Node
{

    /**
    * @var integer
    *
    * @ORM\Column(name="id", type="bigint", nullable=false)
    * @ORM\Id
    * @ORM\GeneratedValue(strategy="AUTO")
    */
    private $id;

    /**
    * @ORM\Column(name="public_id", type="string", length=250, nullable=false)
    * @Assert\NotBlank()
    */
    private $publicId;

    /**
    * @ORM\ManyToOne(targetEntity="QuestionKeyBundle\Entity\TreeVersion")
    * @ORM\JoinColumn(name="tree_version_id", referencedColumnName="id", nullable=false)
    */
    private $treeVersion;

    /**
    * @var string
    *
    * @ORM\Column(name="title_admin", type="string", length=250, nullable=false, options={"default":""})
    */
    private $titleAdmin = '';

    /**
    * @var string
    *
    * @ORM\Column(name="title", type="text", nullable=true)
    */
    private $title;

    /**
    * @var string
    *
    * @ORM\Column(name="title_previous_answers", type="string", length=250, nullable=true)
    */
    private $titlePreviousAnswers = '';

    /**
    * @var string
    *
    * @ORM\Column(name="body_text", type="text", nullable=true)
    */
    private $body_text;

    /**
    * @var string
    *
    * @ORM\Column(name="body_html", type="text", nullable=true)
    */
    private $body_html;

    /**
    * @var datetime $createdAt
    *
    * @ORM\Column(name="created_at", type="datetime", nullable=false)
    */
    private $createdAt;

    /**
    * @ORM\ManyToOne(targetEntity="QuestionKeyBundle\Entity\Node")
    * @ORM\JoinColumn(name="from_old_version_id", referencedColumnName="id", nullable=true)
    */
    private $fromOldVersion;


    /**
    * @ORM\OneToMany(targetEntity="NodeOption", mappedBy="destinationNode")
    **/
    private $nodeOptionsDestination;

    /**
    * @ORM\OneToMany(targetEntity="NodeOption", mappedBy="node")
    **/
    private $nodeOptionsSource;


    /**
     * @ORM\OneToMany(targetEntity="NodeHasLibraryContent", mappedBy="node")
     **/
    private $hasLibraryContents;


    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getPublicId()
    {
        return $this->publicId;
    }

    public function setPublicId($id)
    {
        $this->publicId = $id;
    }

    public function getTreeVersion()
    {
        return $this->treeVersion;
    }

    public function setTreeVersion($treeVersion)
    {
        $this->treeVersion = $treeVersion;
    }

    public function getTitleAdmin()
    {
        return $this->titleAdmin ? $this->titleAdmin : $this->title;
    }

    public function setTitleAdmin($title)
    {
        $this->titleAdmin = $title;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }


    /**
     * Get the value of Title Previous Answers
     *
     * @return string
     */
    public function getTitlePreviousAnswers()
    {
        return $this->titlePreviousAnswers;
    }

    /**
     * Set the value of Title Previous Answers
     *
     * @param string titlePreviousAnswers
     *
     * @return self
     */
    public function setTitlePreviousAnswers($titlePreviousAnswers)
    {
        $this->titlePreviousAnswers = $titlePreviousAnswers;

        return $this;
    }

    public function getBodyText()
    {
        return $this->body_text;
    }

    public function setBodyText($body_text)
    {
        $this->body_text = $body_text;
    }

    public function getBodyHTML()
    {
        return $this->body_html;
    }

    public function setBodyHTML($body_html)
    {
        $this->body_html = $body_html;
    }

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    public function getFromOldVersion()
    {
        return $this->fromOldVersion;
    }

    public function setFromOldVersion($fromOldVersion)
    {
        $this->fromOldVersion = $fromOldVersion;
    }

    public function getNodeOptionsDestination() {
        return $this->getNodeOptionsDestination;
    }

    public function getNodeOptionsSource() {
        return $this->getNodeOptionsSource;
    }

    /**
    * @ORM\PrePersist()
    */
    public function beforeFirstSave() {
        $this->createdAt = new \DateTime("", new \DateTimeZone("UTC"));
    }

    public function __toString () {
        return ( $this->titleAdmin ? $this->titleAdmin : $this->title ) . " (ID: ".$this->publicId.")";
    }






}

src/QuestionKeyBundle/Controller/AdminTreeVersionNodeEditController.php
<?php

namespace QuestionKeyBundle\Controller;

use Doctrine\ORM\Mapping\Entity;

use QuestionKeyBundle\Entity\NodeHasLibraryContent;
use QuestionKeyBundle\Entity\NodeHasLibraryContentIfVariable;
use QuestionKeyBundle\Form\Type\AdminNodeEditAddLibraryContentIfVariable;
use QuestionKeyBundle\StatsDateRange;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use QuestionKeyBundle\Form\Type\AdminNodeEditType;
use QuestionKeyBundle\Form\Type\AdminNodeOptionNewType;
use QuestionKeyBundle\Form\Type\AdminNodeMakeStartType;
use QuestionKeyBundle\Form\Type\AdminConfirmDeleteType;
use QuestionKeyBundle\Entity\NodeOption;
use QuestionKeyBundle\Entity\TreeVersionStartingNode;
use QuestionKeyBundle\GetStackTracesForNode;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;


/**
 *  @license 3-clause BSD
 *  @link https://github.com/QuestionKey/QuestionKey-Core
 */
class AdminTreeVersionNodeEditController extends AdminTreeVersionNodeController
{





    public function editAction($treeId, $versionId, $nodeId)
    {


        // build
        $return = $this->build($treeId, $versionId, $nodeId);
        if (!$this->treeVersionEditable) {
            throw new AccessDeniedException();
        }

        //data
        $form = $this->createForm(new AdminNodeEditType(), $this->node);
        $request = $this->getRequest();
        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $doctrine = $this->getDoctrine()->getManager();
                $doctrine->persist($this->node);
                $doctrine->flush();
                return $this->redirect($this->generateUrl('questionkey_admin_tree_version_node_show', array(
                    'treeId'=>$this->tree->getPublicId(),
                    'versionId'=>$this->treeVersion->getPublicId(),
                    'nodeId'=>$this->node->getPublicId()
                )));
            }
        }

        return $this->render('QuestionKeyBundle:AdminTreeVersionNodeEdit:edit.html.twig', array(
            'form' => $form->createView(),
            'tree'=>$this->tree,
            'treeVersion'=>$this->treeVersion,
            'node'=>$this->node,
        ));


    }

    public function deleteAction($treeId, $versionId, $nodeId)
    {


        // build
        $return = $this->build($treeId, $versionId, $nodeId);
        if (!$this->treeVersionEditable) {
            throw new AccessDeniedException();
        }

        //data
        $form = $this->createForm(new AdminConfirmDeleteType());
        $request = $this->getRequest();
        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $doctrine = $this->getDoctrine()->getManager();

                // node options
                $nodeOptionRepo = $doctrine->getRepository('QuestionKeyBundle:NodeOption');
                foreach($nodeOptionRepo->findBy(array('node'=>$this->node)) as $nodeOption) {
                    $doctrine->remove($nodeOption);
                }
                foreach($nodeOptionRepo->findBy(array('destinationNode'=>$this->node)) as $nodeOption) {
                    $doctrine->remove($nodeOption);
                }

                // starting node
                $treeStartingNodeRepo = $doctrine->getRepository('QuestionKeyBundle:TreeVersionStartingNode');
                $treeStartingNode = $treeStartingNodeRepo->findOneByTreeVersion($this->treeVersion);
                if ($treeStartingNode && $treeStartingNode->getNode() == $this->node) {
                    $doctrine->remove($treeStartingNode);
                }

                // node and go
                $doctrine->remove($this->node);
                $doctrine->flush();
                return $this->redirect($this->generateUrl('questionkey_admin_tree_version_show', array(
                    'treeId'=>$this->tree->getPublicId(),
                    'versionId'=>$this->treeVersion->getPublicId()
                )));
            }
        }

        return $this->render('QuestionKeyBundle:AdminTreeVersionNodeEdit:delete.html.twig', array(
            'form' => $form->createView(),
            'tree'=>$this->tree,
            'treeVersion'=>$this->treeVersion,
            'node'=>$this->node,
        ));


    }


    public function makeStartAction($treeId, $versionId, $nodeId)
    {


        // build
        $return = $this->build($treeId, $versionId, $nodeId);
        if (!$this->treeVersionEditable) {
            throw new AccessDeniedException();
        }

        //data
        $doctrine = $this->getDoctrine()->getManager();
        $treeStartingNodeRepo = $doctrine->getRepository('QuestionKeyBundle:TreeVersionStartingNode');
        $treeStartingNode = $treeStartingNodeRepo->findOneByTreeVersion($this->treeVersion);

        $form = $this->createForm(new AdminNodeMakeStartType(), $this->node);
        $request = $this->getRequest();
        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);
            if ($form->isValid()) {

                $treeStartingNodeRepo->setAsStartingNode($this->node);
                return $this->redirect($this->generateUrl('questionkey_admin_tree_version_node_show', array(
                    'treeId'=>$this->tree->getPublicId(),
                    'versionId'=>$this->treeVersion->getPublicId(),
                    'nodeId'=>$this->node->getPublicId()
                )));
            }
        }

        return $this->render('QuestionKeyBundle:AdminTreeVersionNodeEdit:makeStart.html.twig', array(
            'form' => $form->createView(),
            'tree'=>$this->tree,
            'treeVersion'=>$this->treeVersion,
            'node'=>$this->node,
            'currentStartNode'=>($treeStartingNode ? $treeStartingNode->getNode() : null),
        ));


    }




    public function newOptionAction($treeId, $versionId, $nodeId)
    {


        // build
        $return = $this->build($treeId, $versionId, $nodeId);
        if (!$this->treeVersionEditable) {
            throw new AccessDeniedException();
        }

        //data
        $doctrine = $this->getDoctrine()->getManager();
        $nodeOptionRepo = $doctrine->getRepository('QuestionKeyBundle:NodeOption');
        $form = $this->createForm(new AdminNodeOptionNewType($this->node, $nodeOptionRepo->getNextSortValueForNode($this->node) ));
        $request = $this->getRequest();
        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $nodeOption = new NodeOption();
                $nodeOption->setTreeVersion($this->treeVersion);
                $nodeOption->setNode($this->node);
                $nodeOption->setTitle($form->get('title')->getData());
                $nodeOption->setBodyText($form->get('body_text')->getData());
                $nodeOption->setBodyHTML($form->get('body_html')->getData());
                $nodeOption->setSort($form->get('sort')->getData());
                $nodeOption->setDestinationNode($form->get('destination_node')->getData());
                $doctrine->persist($nodeOption);
                $doctrine->flush();
                return $this->redirect($this->generateUrl('questionkey_admin_tree_version_node_show', array(
                    'treeId'=>$this->tree->getPublicId(),
                    'versionId'=>$this->treeVersion->getPublicId(),
                    'nodeId'=>$this->node->getPublicId()
                )));
            }
        }

        return $this->render('QuestionKeyBundle:AdminTreeVersionNodeEdit:newOption.html.twig', array(
            'form' => $form->createView(),
            'tree'=>$this->tree,
            'treeVersion'=>$this->treeVersion,
            'node'=>$this->node,
        ));


    }


    public function addLibraryContentAction($treeId, $versionId, $nodeId, Request $request)
    {

        $doctrine = $this->getDoctrine()->getManager();
        $libraryContentRepo = $doctrine->getRepository('QuestionKeyBundle:LibraryContent');

        // build
        $return = $this->build($treeId, $versionId, $nodeId);
        if (!$this->treeVersionEditable) {
            throw new AccessDeniedException();
        }

        //data

        if ($request->getMethod() == 'POST' && $request->request->get('action') == 'add') {
            $content = $libraryContentRepo->findOneBy(array('treeVersion'=>$this->treeVersion, 'publicId'=>$request->request->get('contentId')));
            if ($content) {

                $doctrine->getRepository('QuestionKeyBundle:NodeHasLibraryContent')->addLibraryContentToNode($content, $this->node);

                return $this->redirect($this->generateUrl('questionkey_admin_tree_version_node_show', array(
                    'treeId'=>$this->tree->getPublicId(),
                    'versionId'=>$this->treeVersion->getPublicId(),
                    'nodeId'=>$this->node->getPublicId())));

            }
        }


        $contents = $libraryContentRepo->findByTreeVersion($this->treeVersion);

        return $this->render('QuestionKeyBundle:AdminTreeVersionNodeEdit:addLibraryContent.html.twig', array(
            'tree'=>$this->tree,
            'treeVersion'=>$this->treeVersion,
            'node'=>$this->node,
            'libraryContents'=>$contents,
        ));


    }


    public function editLibraryContentAction($treeId, $versionId, $nodeId, Request $request)
    {

        $doctrine = $this->getDoctrine()->getManager();
        $libraryContentRepo = $doctrine->getRepository('QuestionKeyBundle:LibraryContent');
        $nodeHasLibraryContentIfVariableRepo = $doctrine->getRepository('QuestionKeyBundle:NodeHasLibraryContentIfVariable');

        // build

src/QuestionKeyBundle/Resources/views/AdminTreeVersionNodeEdit/addLibraryContent.html.twig
{#
# @license 3-clause BSD
# @link https://github.com/QuestionKey/QuestionKey-Core
#}

{% extends 'QuestionKeyBundle::base.html.twig' %}

{% block title %}Add Library Content to {{ node.titleAdmin }} on Version {{ treeVersion.titleAdmin }} of {{  tree.titleAdmin }} | Admin{%  endblock %}

{% block main %}

  <ol class="breadcrumb">
    <li><a href="{{ path('questionkey_admin') }}">Admin</a></li>
    <li><a href="{{ path('questionkey_admin_tree_show', {'treeId':tree.publicId }) }}">Tree: {{ tree.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId }) }}">Version: {{ treeVersion.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Node: {{ node.titleAdmin }}</a></li>
    <li class="active">Add Library Content</li>
  </ol>

  {% if libraryContents %}
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Title</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      {% for libraryContent in libraryContents %}
        <tr>
          <td>{{ libraryContent.titleAdmin }}</td>
          <td class="action-link">
            <form method="post" action="#">
              <input type="hidden" name="action" value="add">
              <input type="hidden" name="contentId" value="{{  libraryContent.publicId }}">
              <input type="submit" value="Add" class="btn btn-warning">
            </form>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No content</p>
  {% endif %}

{% endblock %}

src/QuestionKeyBundle/Resources/views/AdminTreeVersionNodeEdit/delete.html.twig
{#
# @license 3-clause BSD
# @link https://github.com/QuestionKey/QuestionKey-Core
#}

{% extends 'QuestionKeyBundle::base.html.twig' %}

{% block title %}Delete Node {{ node.titleAdmin }} on Version {{ treeVersion.titleAdmin }} of {{  tree.titleAdmin }} | Admin{%  endblock %}

{% block main %}

  <ol class="breadcrumb">
    <li><a href="{{ path('questionkey_admin') }}">Admin</a></li>
    <li><a href="{{ path('questionkey_admin_tree_show', {'treeId':tree.publicId }) }}">Tree: {{ tree.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId }) }}">Version: {{ treeVersion.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Node: {{ node.titleAdmin }}</a></li>
    <li class="active">Delete</li>
  </ol>

    <section class="">
    		<form class="styled" action="" method="post" {{ form_enctype(form) }}>
    			{{ form_errors(form) }}

    			{{ form_rest(form) }}

    			<input type="submit" value="DELETE" />

                <div class="cancel"><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Cancel</a></div>
    		</form>

    	</section>
{% endblock %}

src/QuestionKeyBundle/Resources/views/AdminTreeVersionNodeEdit/edit.html.twig
{#
# @license 3-clause BSD
# @link https://github.com/QuestionKey/QuestionKey-Core
#}

{% extends 'QuestionKeyBundle::base.html.twig' %}

{% block title %}Edit Node {{ node.titleAdmin }} on Version {{ treeVersion.titleAdmin }} of {{  tree.titleAdmin }} | Admin{%  endblock %}

{% block main %}

  <ol class="breadcrumb">
    <li><a href="{{ path('questionkey_admin') }}">Admin</a></li>
    <li><a href="{{ path('questionkey_admin_tree_show', {'treeId':tree.publicId }) }}">Tree: {{ tree.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId }) }}">Version: {{ treeVersion.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Node: {{ node.titleAdmin }}</a></li>
    <li class="active">Edit</li>
  </ol>

    <section class="">
    		<form class="styled" action="" method="post" {{ form_enctype(form) }}>
    			{{ form_errors(form) }}

    			{{ form_rest(form) }}

    			<input type="submit" value="Save" />

                <div class="cancel"><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Cancel</a></div>
    		</form>

    	</section>
{% endblock %}

src/QuestionKeyBundle/Resources/views/AdminTreeVersionNodeEdit/editLibraryContent.html.twig
{#
# @license 3-clause BSD
# @link https://github.com/QuestionKey/QuestionKey-Core
#}

{% extends 'QuestionKeyBundle::base.html.twig' %}

{% block title %}Add Library Content to {{ node.titleAdmin }} on Version {{ treeVersion.titleAdmin }} of {{  tree.titleAdmin }} | Admin{%  endblock %}

{% block main %}

  <ol class="breadcrumb">
    <li><a href="{{ path('questionkey_admin') }}">Admin</a></li>
    <li><a href="{{ path('questionkey_admin_tree_show', {'treeId':tree.publicId }) }}">Tree: {{ tree.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId }) }}">Version: {{ treeVersion.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Node: {{ node.titleAdmin }}</a></li>
    <li class="active">Edit Library Content</li>
  </ol>

  {%  if libraryContents %}

    {%  for libraryContent in libraryContents %}

      <div class="well">

        <p>Library Title: {{ libraryContent.titleAdmin }}</p>

        <p>Body Text: {{ libraryContent.bodyText | nl2br }}</p>

        <p>Body HTML: {{ libraryContent.bodyHTML | nl2br }}</p>


        {% if treeVersion.featureVariables %}
          <ul class="list-group">
            {% for nodeHasLibraryContentIfVariable in nodeHasLibraryContentIfVariables %}
              {%  if nodeHasLibraryContentIfVariable.libraryContent == libraryContent %}
                <li class="list-group-item">
                  Only show if {{ nodeHasLibraryContentIfVariable.variable.name  }} {{ nodeHasLibraryContentIfVariable.action }} {{ nodeHasLibraryContentIfVariable.value }}

                  <form method="post" action="#" onsubmit="return confirm('Are you sure you want to delete this condition for library content?');">
                    <input type="hidden" name="action" value="removeIfVariables">
                    <input type="hidden" name="ifVariableId" value="{{  nodeHasLibraryContentIfVariable.publicId }}">
                    <input type="submit" value="Remove If Variable Condition" class="btn btn-danger">
                  </form>
                </li>
              {%  endif %}
            {%  endfor %}
          </ul>
        {%  endif %}

        <form method="post" action="#" onsubmit="return confirm('Are you sure you want to delete this library content?');">
          <input type="hidden" name="action" value="remove">
          <input type="hidden" name="contentId" value="{{  libraryContent.publicId }}">
          <input type="submit" value="Remove Library Content" class="btn btn-danger">
        </form>

        {%  if treeVersion.featureVariables %}
          <p><a href="{{ path('questionkey_admin_tree_version_node_library_content_add_if_variable', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId, 'libraryContentId': libraryContent.publicId }) }}" class="btn btn-warning">Add If Variable Condition</a></p>
        {%  endif %}
      </div>
    {%  endfor %}

  {%  else %}
    <div>No content currently added to this node.</div>
  {%  endif %}

{% endblock %}

src/QuestionKeyBundle/Resources/views/AdminTreeVersionNodeEdit/libraryContentAddIfVariable.html.twig
{#
# @license 3-clause BSD
# @link https://github.com/QuestionKey/QuestionKey-Core
#}

{% extends 'QuestionKeyBundle::base.html.twig' %}

{% block title %}Add Library Content If Variable to {{ node.titleAdmin }} on Version {{ treeVersion.titleAdmin }} of {{  tree.titleAdmin }} | Admin{%  endblock %}

{% block main %}

    <ol class="breadcrumb">
        <li><a href="{{ path('questionkey_admin') }}">Admin</a></li>
        <li><a href="{{ path('questionkey_admin_tree_show', {'treeId':tree.publicId }) }}">Tree: {{ tree.titleAdmin}}</a></li>
        <li><a href="{{ path('questionkey_admin_tree_version_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId }) }}">Version: {{ treeVersion.titleAdmin}}</a></li>
        <li><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Node: {{ node.titleAdmin }}</a></li>
        <li class="active">Add Library Content If Variable</li>
    </ol>

    <section class="">
        <form class="styled" action="" method="post" {{ form_enctype(form) }}>
            {{ form_errors(form) }}

            <div class="form-group">
                <label class="control-label required" for="library_content">Library Content</label>
                <div class="form-control">{{  libraryContent.titleAdmin }}</div>
            </div>

            {{ form_rest(form) }}

            <input type="submit" value="Save" />

        </form>

    </section>

{%  endblock %}

src/QuestionKeyBundle/Resources/views/AdminTreeVersionNodeEdit/makeStart.html.twig
{#
# @license 3-clause BSD
# @link https://github.com/QuestionKey/QuestionKey-Core
#}

{% extends 'QuestionKeyBundle::base.html.twig' %}

{% block title %}Make Starting Node {{ node.titleAdmin }} on Version {{ treeVersion.titleAdmin }} of {{  tree.titleAdmin }} | Admin{%  endblock %}

{% block main %}

  <ol class="breadcrumb">
    <li><a href="{{ path('questionkey_admin') }}">Admin</a></li>
    <li><a href="{{ path('questionkey_admin_tree_show', {'treeId':tree.publicId }) }}">Tree: {{ tree.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId }) }}">Version: {{ treeVersion.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Node: {{ node.titleAdmin }}</a></li>
    <li class="active">Make Starting Node</li>
  </ol>


  {% if currentStartNode %}
    <p>Current Starting Node: {{ currentStartNode.title }}</p>
  {% endif %}

    <section class="">
    		<form class="styled" action="" method="post" {{ form_enctype(form) }}>
    			{{ form_errors(form) }}

    			{{ form_rest(form) }}

    			<input type="submit" value="Make Starting Node!" />

                <div class="cancel"><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Cancel</a></div>
    		</form>

    	</section>
{% endblock %}

src/QuestionKeyBundle/Resources/views/AdminTreeVersionNodeEdit/newOption.html.twig
{#
# @license 3-clause BSD
# @link https://github.com/QuestionKey/QuestionKey-Core
#}

{% extends 'QuestionKeyBundle::base.html.twig' %}


{% block title %}New Node Option on Node {{ node.titleAdmin }} on Version {{ treeVersion.titleAdmin }} of {{  tree.titleAdmin }} | Admin{%  endblock %}

{% block main %}

  <ol class="breadcrumb">
    <li><a href="{{ path('questionkey_admin') }}">Admin</a></li>
    <li><a href="{{ path('questionkey_admin_tree_show', {'treeId':tree.publicId }) }}">Tree: {{ tree.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId }) }}">Version: {{ treeVersion.titleAdmin}}</a></li>
    <li><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Node: {{ node.titleAdmin }}</a></li>
    <li class="active">New Node Option</li>
  </ol>


    <section class="">
    		<form class="styled" action="" method="post" {{ form_enctype(form) }}>
    			{{ form_errors(form) }}

    			{{ form_rest(form) }}

    			<input type="submit" value="Create new option" />

                <div class="cancel"><a href="{{ path('questionkey_admin_tree_version_node_show', {'treeId':tree.publicId,'versionId':treeVersion.publicId,'nodeId':node.publicId }) }}">Cancel</a></div>
    		</form>

    	</section>
{% endblock %}